# Generated by Django 3.1.3 on 2022-10-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221026_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_right',
            new_name='is_correct',
        ),
    ]
